### ISSUE TITLE
[Optional] Publish to azure sample browser

### ISSUE THREAD

**Issue by hemarina** [Azure-Samples/llama-index-javascript#16]
This repository is added to [awesome-azd](aka.ms/awesome-azd) site and it is a Microsoft-authored template, we encourage you to [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main) if you are interested.

**Comment by v-xuto** [comment]
@manekinekko Please copy the relevant content in the [readme](https://github.com/Azure-Samples/llama-index-javascript/blob/main/README.md) to "docs/readme". "docs/readme" cannot only contain metadata, otherwise it cannot be published successfully to [learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main). 

More details:
![image](https://github.com/user-attachments/assets/513ddcfa-1ee5-44dc-a5fa-4b6a54bf427f)

**Comment by manekinekko** [comment]
Hi @v-xuto does this look fine? https://github.com/Azure-Samples/llama-index-javascript/pull/22

**Comment by v-xuto** [comment]
> Hi @v-xuto does this look fine? #22

LGTM.

**Comment by manekinekko** [comment]
@hemarina @v-xuto Great! It's merged now. Sample should be ready to be published.

**Comment by manekinekko** [comment]
Amazing! Thank you!
